name: build-builder-image
on:
  workflow_dispatch:
    inputs:
      registry:
        required: true
        type: string
        default: quay.io/modelcar
      image-name:
        required: true
        type: string
        default: huggingface-downloader
      context:
        required: false
        type: string
        default: builder-images/huggingface-downloader
      containerfile:
        required: false
        type: string
        default: ./Containerfile
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true
      hf-token:
        required: false

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        arch: [arm64]
    steps:

      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ inputs.image-name }}
          context: ${{ inputs.context }}
          containerfiles: ${{ inputs.context }}/${{ inputs.containerfile }}
          build-args: HF_TOKEN=${{ secrets.hf-token }}
          platform: linux/${{ matrix.arch }}

      - name: Podman Login Debug
        run: |
          podman login quay.io -u ${{ secrets.registry-username }} -p ${{ secrets.registry-password }}

      - name: Push-Image
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ inputs.image-name }}
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}
